version: 0.2

phases:
  install:
    runtime-versions:
      java: coretto11
  pre_build:
    commands:
      - aws s3 cp s3://reimbursement-api-bucket/application.properties ./src/main/resources
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./project2.jar

artifacts:
  files:
    - project2.jar
